### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ozgunbabur** [koksal/tps#10]
Hi There, 

I tried to follow the installation guide on the front page but run into an error.

After doing 

git clone https://github.com/koksal/tps.git
cd tps
./scripts/run

I got the following error.

[info] Loading project definition from /Users/ozgun/Documents/Code/tps/project
java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1130)
	at java.base/java.util.regex.Pattern.split(Pattern.java:1249)
	at java.base/java.util.regex.Pattern.split(Pattern.java:1322)
	at sbt.IO$.pathSplit(IO.scala:744)
	at sbt.IO$.parseClasspath(IO.scala:859)
	at sbt.compiler.CompilerArguments.extClasspath(CompilerArguments.scala:62)
	at sbt.compiler.AggressiveCompile.withBootclasspath(AggressiveCompile.scala:50)
	at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:83)
	at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:70)
	at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:45)
	at sbt.Compiler$.apply(Compiler.scala:74)
	at sbt.Compiler$.apply(Compiler.scala:65)
	at sbt.Defaults$.sbt$Defaults$$compileTaskImpl(Defaults.scala:789)
	at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:781)
	at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:781)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
[error] (compile:compile) java.lang.NullPointerException

I am on MacOS 10.15.5. Any idea why this can happen?

**Comment by koksal** [comment]
Hi Özgün,

I am guessing this is due to the minimum Scala version requirements for JDK compatibility. Right now, the project [uses](https://github.com/koksal/tps/blob/0162a2fffe40b430090188e421b2b3cdd2d14434/project/Build.scala#L13) Scala 2.11.7, which is compatible with JDK 8 but not with later JDK versions (per this [doc](https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html)). I just upgraded from JDK 8 to JDK 15 on my Mac, and I could reproduce the issue.

Unfortunately, the migration from Scala 2.11 to 2.12 is non-trivial. It requires bumping up the sbt (Scala Built Tool) version used from 0.X to 1.X, and that in turn requires a [migration](https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html) of the project definition. It's not hard to do, but I'll need confirmation from my current employer before I can submit new code to this repo. I'll be looking into it.

In the interim, I'm afraid the only easy solution is to run the tool with JDK 8.

**Comment by ozgunbabur** [comment]
Hi Sinan, thanks for the quick fix. I checked and it works now.

I have a quick and unrelated question if you don't mind. How can we use TPS to model proteomic differences when we don't know the exact location of the perturbation on the network? For instance, a cell type is treated with two different types of media (e.g. bovine serum vs PBS). In that case, does it still make sense to use PCST? Do you have any best practice for such cases?
